# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ExportToRF3D
                                 A QGIS plugin
 This plugin exports the prepared datasets for a RockyFor3D Simulation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-09-25
        copyright            : (C) 2018 by Valentin Marquart
        email                : valentin.marquart@tum.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ExportToRF3D class from file ExportToRF3D.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .export_rf3d import ExportToRF3D
    return ExportToRF3D(iface)
